apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-9-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBCND/rYnlmaGEYs5GMpCyi1SIHn1MUADZKXSunEg0NsNPzGHbRPOlj/9pv566+n5tTrhVbQIKwqvpjJudu1ueJhMPezJGYmqLLjM280ZZ4IIsvfWMxhB+d00jE92rHk/7CppmgxDZkYLyhoAGvEhppLW7C/XnWn5HKRoe1gdZIM+U1IIU6IdaUUlA7+qfWadfgxMiJQqMRDu68lZR5IuQvJ8BFOkXHgxCdUe+Kx9ZecuYQWmm48/6OA4dmSvEt2nTC92WezXYOeH6bwSsUs577MaQBFmWy1JuFPhWixmgRrl/dTC/uyJEM4SRc9f/Ew0Hr22Tnif8GZEsrBqXdXHXO9/gf5iYO/zYhGZtzL5s9hq4GnGwudko/7JNpL3b7bV4ioZYnOn8qUEE4/Y8O0IkwzjMSUHujY6Rqn2Exx3BUhhfpB6i2FqXK43jaU0+W2qzn/HTWXMVJUOP289Z8Z/qKXM/89MSUy3hFqb/dQUlzvaRWEegbPLx2xNhg3W/+1PPtj9sbydg05pgUgobrkuEc5YAafjUYYMhvzBryc3Dnn/gJx5iaG4kJcsbSfUi+4JxfGthhs6S8LSzNeOXPx5zAzFinEuzdz7u02qRAxuxQn9ojD5FVpilOCcz6X5pScANiIDybdfofd8RXXjEpwP68LD3Vr68/V9iS/FV7qwGqN/OUnJDT6K2CdIGRglei3ETdqa/19w==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-9-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBLXXt57DzYYVVVWoYQDsNIzmwwwDlhHsxahFncZWf+QZv4M+oJ9uxy89UD//VgFRZp9wVw8Jhc3AYbfLKulLaok7Hy1I8z/PS5AMc9XgbZkhywmNqJF0/u2W5XHpB1t+1XH8gqwJpqxIYu4s4x0h/dsElladaZgxuEscJ37/netBUxVnY4sqE8LDI2cAOidd37lWRlxu+YrzZIF//dv8qwOw6tKdbT+J4zqvFZs24uaGQ3c2UNRUSzs/ELyJXj/D8zD9VpW68txdT9eehavv9WFuOiP9OXrUdUfgGuXmeaCV2Xkw+n8O6p1CErvvtlnX37l/IP+VxJWHZkMq0vtgXJVDfArpEtnYLGU12E08x+GjRk7cB+6RMquQDIdw8V9h8FOiDcS9HSB5KMnft4fv0i6HOVgp/M/EasAWgSLb6XUZP+LyBpHWDVBehImfa0jySz17IzC7Tl50BKNTSEH8I/aMl2QVNEI12U+xFQo9O8ADMX09FRhzvaJurMjw1vnv1R/yXlFRjkNQ3N7NHGO4oAciimVTyVv1NFakY16D8/t1WhhfJQRU/3QavXJiHg4YvYgYbxcNsU7gBJVnmyc73O5jyqtkuDFDLJeFjcC05V5v0Poc8WkcQ9gKWVf0wV2v80CulLhz8WwOvDV4H0uqPpmx9USqDHu4lQQ5yUQWSHicZLEVIC9UVsDsmVILGJqA6GCxpJYg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
