apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-9-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBBIrRxplQsU2NZNM32KSEDax+riwsOI+A7yuHg22qAmDyY7vkFAYT/og2kQifSCbboQT+6uGm0dqw26OFAfcydeV3LS5Qjig2WMQN7x3o7tq23mnz7HclQwvR6ZBe9HNNoJjqtSxNfMUczlo94LtPVWbYhYMHPK07SVctkB4ywxgYoa0sOqG7Wp/PzkVpsO6payb8E2UvtKTKlNASxcyRNKlEEEu7BnfRP4OWYIDDunwUwPFEDDcyCo09GR0Q3/3DiPhIPXX1VhGY6GTV5G/ZfIXtHFGkIhXbjxnd9bePnsG7F2vnEXhB4uvzt2w4wFhWN96ALxcN+GThWYLx6RL2HpS2l8xgtzeLkjCp4k9yvDAzprQN/fRbO4ORzmkQWlGs7H+VYgZPeOENEjJ40lbQ7xXdoIex/z3lZEs3QHVkRy/NMw7MJcVrAYssU+OEURtmp1o1jk9hVbTreYvwwXFs0FIXpPDLZssP3i7zeEbulT3rgop3Zo4uQJv+bEyjmxAHbGFcXTbYoJMrCrHgiiNEgVIcV7LlPLhliKaRXIsZ8QrYspDWa/u9tzgOPliE2QaPuSjLVYgZbaXQXGzVyRT1ffcnnrWcPR5OBbQ44BJ3w890V2CpB/1sHMURVK6akAs+PYVIP5atGMzxz1APOIvYO2zQZ8K5arg3njC+HpeWqnvnPdXV4CAPZVIP0x8DLyNj3OgnKhw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-9-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBlA4hc2unD3SrM0uTJWWFMP/exMDPMKPca5fY+v+wXQ3nPc2p5EvL/cwneZMnVOKl3y9CBrfPCTayDrAjS2tzPxbWRovzE4847V1dQ1Qql8QbCP+rmchIT1rZTHcA6soBnpx2ZsDrd+mc6Phmf38tr7Kwutwf+R8Oya1HsMBAG40a+8fnsScaijYNaV9qkVuJqJiBztk+pD480QZBFKIu+fu2Q9y0lcZrcX5WZwr9rR9ucAMg+YrYoNdpQVGG1U1AhZOz/q3+S8Pt/V6Rgi2CcUOdrBtA3ONArgTE/2xT0tAF0rNJsarPDHOZhe9UkUaLoNFGyOr/HqGB8Z5aLIOp+P+GRo+Jm7rUIV/ic3o+SKQFduyGe5BbvnQIhIHiI5sjHBSTHwFaAz1Om2U4vl4Sa+jJi7JRPgpvaYgmnSgp0wg2TI4y0+h/WV0ESot6e32PEtQJgF/eVrkV1VASHcqjuy6w89bHsPmFcjEXI8SWGAHodY6NAJUgCOHj22vEHcDEcZi88z5S79bdIsUF4wT4q1AB/Ei9KAFfLTM6gOcd9sNFNIXc5WPqD/DMOTTyyWof0oimP9guDaBcx0vBG9YauGYUHjQdnb9Pe1IionOYbQCbZ+jKe/oooF7MaHOmhJjsV7KgufFJ9Wr2KkkJgFGCfrnuKVqQRndHuTcArDezwwYF1pLxzJeSIka02LBlsbOI9fUx/sw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-7-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgB5IvNaJUT2btWKWXGB70GgFOI3gKumRN49qOyRgrLGfURHs78PczVXCqNoHDOtKUywd192gF/PUloGoV+VuHsF/nbQOZo4zvno4PYP6AdGuwrgDK0P/09hdYxZ5S2ZK+n2M65m0+oJ5Yv8qOHTeAVKpHtx6qdxRBjFRumHzlI0IvSvkf+0s9xkqua6WaekIwp4isi6A/5AVuOG7FTTvKK0QyCY2wkb3tVakUSpuRPPruPXl9m/AZJ9v/0uMWGOEsQVrncshQJ1puXzypQy6V/3Gg5mqMnAk0kvP8VlE6luVTWQsbZPIWG2R2sy+lD3EoOd3xmE30uCbBlAjrgQCw6IbvX1a6MN0cU/9Nus8pgB4RF09pHyW6toEmWFrIJicqdyOWt0bRlaItsQ0s+FWWNLW0yuoJc2u6VYtdveA0VwtMCBvGXi5JdAI78smacUfrutkY8U8dwthtJphyjOzVYckDivpnS8fQzp8SxCUqb50XEtocwvwgXrPJsjdtNAVIigRzzaj2UeBQJyxKEeZd01gftlgLJnpl4Wg5tZypNMW8R4LZ6GxPC+cInS749XwIOT29YTH2nNNHquNCasUUjxYETwc7kgTcUwVmSAatwIcRowiS8tX4fHu39HAp82uJGpRCtjlJMatEupty3LBGB5vzYRTqoTARnUKEhsOvwxR0SzOtqlbER2RanQR7JW+RC+uELEKg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-7-secret
      namespace: postgres
    type: Opaque
