apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-9-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBUVdFaF8v8J66AOFRUh2DjmvQphYD01ixNn/i0Koq93hs+J2DghwqDvAnoiT3Nz/C+cxA6/ARKodbtVtCItQ9sfmh5e3ER4XbPSt2YPWcXcawa+d4fB+pF13GpUFQnRp94BYiZSzq+9CUGYzWOWa0dd0Qsy5uqBo4fvpoeANlUoY0oi+by/HbsPeQ40FzAtFaRX4i4ob5AAO0oosMZGdNOChPOzwHac2zn9ewS7LLlGkBNFOxy6cOrP8uNDgOlkfwFxO/e3SpPcsRkalZskaEz6B3P8HQGvl5TPg2/mFJpc6enwkxI9UilGCvIvGhJ602RqmL1GqNqv5Btx15pHsibX5X77MHBstXEKQTY08V42o34zp6cZmZZxNNxo75N23KSdYFmYUBPlRA/hi2jg3IKjkk58nq3riluS4W2bvajXR+VnvjPues4swCpsQCY/QDfr7K9rMwCciffM7yti8zaOXuLz9s2bjPGE0jecTFFcy668TC1lIafOKPfGd1z88Z/AM8kD5Kz90qlhAQbrb9Y/548k6gLKO7bC7R6CpY9QJ8Z6KZK/xcDAU7IW5hpUgvYy8XCE0h/MHMEtT6c9FCg/49s87VnGBcJAjpmVV7yXl7VMP/op7d6OUT2jk1Jd6jFmLjOo4ti2RHtPKM5o6EBv2AI9ZdeuKc0bHLXDSU7GN8d1FocxxbSKHdw6nze0FOUHuGCfw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-9-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBATXLRN9pX74G7qFY4SUIlf8JIIf8nYUhvt3qWwTMTmibffHb2mDBhv0jvqLxYbzT6WhVQeylwZTsL0bSo8iQAtGcy02czRfD7bm3Ygm0l51LlgEDB34lptf0x8eCDu1xmZ3U+gtShfAW6Lkr1CFSArrhz9TEKVBWoUHBIj0XbJDwPh8GEcnbV/6f2XQtm8e0b+XuOO4OrvCZtcJawpIGssMp10Bgic0LWOasPEMiOPWUIOelQOyybXPv1cz6cMj2VkZFnynqZf+OEWt4lUT2771o9/jElJY1cY+m5kgrFeWhinn7RbQwSdBzpnR/3h6X+A2wkqGgnTOugX+g6gjN07I7u0FcNG3mpTORW6GSz+13dC3LfSihDd5u9r/YsoD564SrRJCW6yAbCM8tLikVAvPXDxAUK8ganf4XPyceu+wVA6UuUKAsgdkYyJ7XF3VHBVCjBfZG7GtYBq9qe9xiCvJqSZyOqpvIt0/ZTmiIoWLsbwYIdLmN6GMbFw2m1eP1UnUCAui9LQF9SIO0utgaIOJyM2Frr3uQv4LeSexahuYTgiF3A3uPLHJCywks7ESFA7c7tMLClKIATnEcTqkI6CqCF8zqb3RgPmHQ5XQ/WALpYCIpuVXaPcYRYQXEamPlkIZ/HXlIQ/4pCD6/4bqWghUTg33yFXjsv0lnR8onlRRBp8vS6bLhNHPZ9elGjCGIwe6zovg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-10-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgClJqtTXNDH3GMIav5OE37Zl2bpjYiKt0EJlCZmwPp9GKuhhwzmJ12pWqwaigfF+iVjnRoDlOW6TVzoh8jxIGnEm4sh7oVbiGpkQ4v63RG5c8vXn8kScArCE4vT/3QaTxNsutIcgSVvtkd8FLVcVNIV+5BkyxZ/YyM5IOk+CICleLCzM0TlvvR5dQqMDfP9XcOV5S5HObpK0+lqqXWMWD1jCQ0LLoq4bf3cEsbjEbJTqtIWkuRiiwqv2JfxaiGbLhK1v1QGxle9/2SpaQMZiG+lcCHHVQemFKW0bjlr1i2oPwvvu+sVfrtzWzYDuLr+l/9jS6BlzfgJuCI66Q9vrhJW4XbC+MTabrTcdbXHU4yn+1T186uFKbPKS47smeL9iIKIbOtCJCvmP4TFiaGDli9iEff5rtECz3XdtkXln+xm6+NJcuApPOJxmeXXdw5nTFfiOHKAyJeUjRYAV3JTwCHkvNVPP+30szhc8B1Bo6XhZqoT/XTWHurf051T2UwTJkEvmRWlB9uLra+eBkj4RJDQXY1U3ib+hJvyUsn687rU9A5ZnCwlGQWht9iWfzxABTYaKnHOnaY+aK0fftw79QvkFBd/WWi99zLj+nRXYqpQm/R+F88Nbt9klfl+xKk0qO72DVz52LQ0gjWrsth1nNBaw+Ri+O9Mj07fpKP7A65rvMORXfLxWu702LWl6kU5GcW3CCwqnw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-10-secret
      namespace: postgres
    type: Opaque
