apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-9-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgA85tUWXUK5N9d2WIckWfsMqjCieXXMlcjo61RzRXWtlH8ZOX1bqRzDIzSgaNRp/kLHooq4OdOKmLjfMU9BW3Vm7RkpQUb3O25gMUS9p6xE2iqrOFDcprtlaHcqEVTVYBliUUhQYlpUoGAnv0/fLm3OYU4SeKqih76sLcioUUpUTFUN/+mEqz+guZC12WRBb2nfJLkX6XeUX6JqwzSWcjpBWQqdRy7kJnTvI6h9Auaok1/4TMXkM8FS/ycXi1ddzgmk4F2ATcochjHTGDxaICfVoAEkbvUjyQN5bluB+2hdyofhAl5USI0mffNSflWg6wQu1ojM6vzz9X05eefrO1dIX10zsAQjonCSl8RRk1QHMcD0QkZDDxJYDr9uXtsEMt49nZ4e/nRUTiwonuiTOP2ZhYJCOZCeOOGFeayL5tgA7ycXyYa1w4iEwibrHwVnwBfCMDnigFj4JbgIGpamXW9foUXukWkvEuDeeN8uA6zRlr7ao9np5YjzVfiKOnUWX/xg/RscyzJ7Jpqm7x7HM2Ipcmp0YJD5TM6dB9utGC9FKWbeocPyh/zIF9aO1jSMnMqfw7ERNSibMGwp9QuOFaYp4+kxz8kuVct85BXmGxaszYYOIwO3bwEKIwKn7/apprhJTPuJEDMz/UFoZ41h6Q9WFqO9YE/XnR3w38plZT2WUcKPXgK2k8ojRLPIJ93Z3bOtWmXZwQ==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-9-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCHlnujbTGyziOl55wXcUm1TY8GWhlwVpoVt2yC5Bi+Dt483d9MTM8dImAzR/BSzqMBdOz9D3o9LU/artG7rdw6qq3CzaAbuqWco4tcMpnyhwRNIz4PUG6er5s9LmYyew4HccjT0fdu1UI/3R9BCEK/hqjH2OX0H0uNNcGi4kMs2G7E7wer9RrfMsKd5JO0bT58/P+zvehqmybB8JunlyMrC5HKlMUDI1leIVoQn6fkF/Rvz99cVyTcWUPAXpBid2M1QHL+cvp/Nn1qu5tfBWTvMb9Sp4IcDHmk2gok8+MfgC4NjLsDCWsBTO3sOm16l5kgx96f8fGUhN6Guvcw6wFHdbsz+y8IeLSxbJiInN/O9obOYZ9VKdga5lAUBuJfmtfMuOavQzh6PcKkRmo8hGyh4MXbOvZvOvgOtgfXSdtDhcFMXzPPOChZyFu5iq0q6iZGUTNH2Wpg0S4BIXDtRo/yCp6obv+5sHZOjJo/U7G5EI+7BfJAXEWbZRYElF+n57vSuoMuca9OcHnxKMPWJt80srghvdkcmuXMzvFEbp3Y2oP48PheAv8LTSmV+stBT+DNPtjh6WphS9abdWkUVv3gPR/VKwXnVXUVynSGT9mBuAgqPMNgsEsRxafJv7Xy3UnIWaNeb+y/3UU8KPHExfR1rQ/MnfSjEVNFQ52HwoWRErbOXQRoXv5CMGqMTl+LeVdwb8WLeA==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-1-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBPBzsC/NdO0x4uwnRzsN2dKr06nJLCer4rqNR1+dlYhBAQMyRBQeji74mOgdMqWHbvYfgQO0LJOx2aGp2lHzWkva59xTJN7gX5SXOBZC0JtfgIcSmNay5Qw6jLH048eIogWR71tuDwCN/qbDtW9XAz1RskgM4jYtXWedkB53YNMWwwQ0Ao0/SvB0Mm12tSIFiJ4V2ug6fxGT8H0GJXrjEhc1sWekmpiaI778hDczxA91h6ji34JWNU37BGbvBKZQJFOhHJoZw7aH+o4klFAFNz2viumTHH6MgMmee/qWlj4gqEFfbcGoi29Y0DYhvJBtt8GUyouPTcdM1iIpeLbl3+n5VkWpEPb4JtDPuXI4fF58P4uF5EMCTuflKS6omTd6YQkROqYm4nSHrhtsWPpEBgNG1FnqV5YbAQX3UPWbutgwssxbU2+2A+gT3t0RNE0PEJ3fmobb+aTRancYv5ib5niS8hp4q5amTaBlC2U0nJTnZ5KpQXzx6IewQjQ0hoNZ9244mQjDT8OAl+BUJyCDopEpQUTy+xuRZOK2N7HPN2HXYzKa9WoqQUVHVb+o7q4lGyRk0RtyBpL3gg6ElyumFP28wnsWQVpZsfS2f/Ak07doXwgPDhMgYkQ2LOWeQ6h5YrR1o4by8T5uYlDDjFhSdFIxRGPr1ScoYvMev6v7aCsp6pjmb8QYGICW5OxdUdbt7uXv5wWg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-1-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-2-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBfKoknKFx8R6tVUYtAdLOhpCwwkA2Qm69MPjJHXlls6dwYpLE0Jqjgtd+VD2ht6/uzwtNbCnk7fUE0cH4PkSj7q9GTK1w5HpEu17/zQ9Dd6J73EgxemyJxDNTjLcFn1hk3iQFhmK+GtLVXbf9jlS3K1/m6f+R8VxOLt8ZBrJFSJBJ42NLpDdjPT+mKCUs2T08arsuxrAWiCO62yLqamWNUNyzVk7SAreimbwDNFkqxJiQWXSiqVYgJ2IF7zjG81lFC0+ociXZrdXhJwbBWE9o7ZNPPTE7odMl2lvt+8P9l80YyqlvaxdYqZTOqQiUufLXoXopMOpAOiUWvzsG8KGk2fGMEt1kJh49zhSUQ6lHwh/Fgtflxc5DCXyd5jaGatcwSdFRBas/pU+/O0VF0c6mrPKZ7bHs3PCQq7Q2UfyVj1rx3s6UibNXNGdys3DYC2OpL6J+KYy0Q0uympB2zB0U4M3HjmQFVd9PCE3p/ZI/bAfAaSa59XFlSFDlXPATHc8E6MFMrJ5mtcEjCaqGIIn+dSxU+BZxknR2WEHqai+7AUKEcYQo9iBuAf/e3B+lYolic8Ch/nkOJIci6mGqmwq9iTTyGZXEmvdNoQ4StELDGa9cy6vPtfThFC4BnW8aK/MLSWhNJ2r9pethn7QcOrqRCSyPm0jVOdCPomG83GVv91reoe8d70sJp1mUM148pRhHhJgaEyg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-2-secret
      namespace: postgres
    type: Opaque
